### ISSUE TITLE
Develop/Integrate kube-rbac-proxy

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-explorer#4]
Reference: https://github.com/brancz/kube-rbac-proxy

**Comment by Abirdcfly** [comment]
![image](https://user-images.githubusercontent.com/5100555/229050671-e62c383c-2b0b-489c-a3ba-d37f3949b9a6.png)

We have two different options：
1. using kube-rbac-proxy
2. developing a simple authentication middleware.

**Comment by bjwswang** [comment]
@Abirdcfly before we really fork and update kube-rbac-proxy, maybe implement core functionalities in this `bc-explorer` via `middleware` ?

**Comment by Abirdcfly** [comment]
Because we may **deploy bc-explorer in other non-kubernetes environments in the future**, we should adopt option 2 and write our own middleware for authentication to facilitate expansion.
