### ISSUE TITLE
Fix the problem of missing parameters of mirror building

### ISSUE THREAD

**Issue by 0xff-dev** [bestchains/bc-explorer#52]
0.293 + go build -v -ldflags ' -X '\''k8s.io/component-base/version.buildDate=2023-07-04T02:04:25Z'\'' -X '\''k8s.io/component-base/version.gitCommit=945729eea26f0aedfbc7cf2f237a8e5c54fcf1a6'\'' -X '\''k8s.io/component-base/version.gitTreeState=clean'\'' -X '\''k8s.io/component-base/version.gitVersion=v0.1.0'\''' `-o _output/bin/linux//observer` cmd/observer/main.go
...

[stage-1 2/5] COPY --from=0 `/go/src/github.com/bestchains/bc-explorer/_output/bin/linux//viewer` /bin/viewer

[stage-1 3/5] COPY --from=0 `/go/src/github.com/bestchains/bc-explorer/_output/bin/linux//listener` /bin/listener

[stage-1 4/5] COPY --from=0 `/go/src/github.com/bestchains/bc-explorer/_output/bin/linux//observer` /bin/observer

---

As you can see from the build log above, the `OS` is fixed to linux, and `ARCH` can't get the content.
Please refer to [bc-saas-dockerfile](https://github.com/bestchains/bc-saas/blob/main/build/dockerfile.bc-saas) for how to fix.

---

expect 

[stage-1 4/5] COPY --from=0 `/go/src/github.com/bestchains/bc-explorer/_output/bin/linux/amd64/observer` /bin/observer

**Comment by bjwswang** [comment]
@zqq454224016

**Comment by 0xff-dev** [comment]
Any progress?

**Comment by 0xff-dev** [comment]
Refer to this [PR](https://github.com/bestchains/bc-saas/pull/31/files#diff-769644b7881cf293b7fe935a4305e498239025db3f4c6660f190cf324b0439fc) for changes

1. Modify the `Dockerfile`

    go itself supports cross-compilation, so we need to pass the target system and CPU architecture parameters to go.
   The final result is:

   ```shell
   docker build --build-arg OS=darwin ARCH=amd64
   ```
   
   [Reference Doc](https://docs.docker.com/engine/reference/builder/#arg)
   


2. Modify `hack/lib/docker.sh`

    the function `docker:build()` is the command to build the image, you need to follow the changes in the `dockerfile` above to add the `buid-arg`.
 
3. Modify the `Makefile`

    Add build parameters to `make image`.
